# Generated by Django 3.1.3 on 2021-01-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exer_calories',
            field=models.IntegerField(default=0),
        ),
    ]
