# Generated by Django 3.1.3 on 2021-01-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_auto_20210126_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
